In [30]:
import pandas as pd
import numpy as np
import os
os.getcwd()
import glob

In [31]:
import pymongo

conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

db = client.dataquality

In [23]:
glob.glob('*csv')

['heat.csv', 'nakisa.csv']

file = "nakisa.csv"
errors_df = pd.read_csv(file)

In [24]:
errors_df.head()

,Unnamed: 0,Company Code,Company Code Id,Date,Date Detected,Date Last Modified,Employee,Employee Group,Employee Group Id,Employee Subgroup,...,Position ID,Product Group,Record Last Modified By,Record Last Modified Date,Region,Rule Description,Rule,Rule Name,Severity,Status
0,0,Rio Tinto Services Ltd,9040,30-Jun-18,9/16/2016 21:43,6/9/2018 22:28,Michael Stross,Regular,4,Q2,...,251293.0,Commercial,JINFELIZ,11/30/2017 0:00,Asia Pacific,Employee with invalid Cost Center,1912,12. Invalid cost center,Medium,Auto-Open
1,1,Rio Tinto Services Ltd,9040,30-Jun-18,9/16/2016 21:43,6/9/2018 22:28,David Goodwin,Regular,4,Q2,...,30483374.0,Commercial,MCUBILO,4/9/2018 0:00,Asia Pacific,Employee with invalid Cost Center,1912,12. Invalid cost center,Medium,Auto-Open
2,2,Rio Tinto Services Ltd,9040,30-Jun-18,9/16/2016 21:43,6/9/2018 22:28,Llifon Pierce,Regular,4,Q2,...,30819404.0,Commercial,MPOONS,11/30/2017 0:00,Asia Pacific,Employee with invalid Cost Center,1912,12. Invalid cost center,Medium,Auto-Open
3,3,Rio Tinto SG Holdings P L,9630,30-Jun-18,9/16/2016 21:43,6/30/2018 22:52,Tugsbold Bayanmunkh,Regular Global Emp,5,R2,...,30698529.0,Commercial,SRAMOS002,6/6/2018 0:00,Asia Pacific,Active globally banded employees excluding EXC...,1939,39. Active globally banded without a valid IT9070,Medium,Auto-Open
4,4,Rio Tinto SG Holdings P L,9630,30-Jun-18,9/16/2016 21:43,6/30/2018 22:52,Lynda Lian,Regular,4,R2,...,30394726.0,Human Resources,CDELUNA,5/15/2018 0:00,Asia Pacific,Active globally banded employees excluding EXC...,1939,39. Active globally banded without a valid IT9070,Medium,Auto-Open

In [28]:
#Average errors by rule
grouped_errors = errors_df.groupby(['Date', 'Rule Description'],as_index=False).sum()

In [29]:
grouped_errors.head

<bound method NDFrame.head of           Date                                   Rule Description  Unnamed: 0  \
0     1-May-17    A - E, EXCO Bands and Exec Mgmt EEgrps mismatch         957
1     1-May-17      Active Position outside the OrgUnit structure          75
2     1-May-17  Active globally banded employees excluding EXC...        1595
3     1-May-17  Cat 1 contractors (excl. Project contractors) ...         899
4     1-May-17  Cat1 contractors (excl. Project contractors) w...        1231
5     1-May-17                 Employee FTE less than or equals 0        2459
6     1-May-17                 Employee Full Time FTE less than 1        3018
7     1-May-17                        Employee Job = 'Contractor'         293
8     1-May-17                    Employee Nationality is missing        6498
9     1-May-17       Employee Part Time FTE more than or equals 1         246
10    1-May-17                  Employee with invalid Cost Center        4420
11    1-May-17                          Employee with missing job          19
12    1-May-17                       Employee without Cost Center          18
13    1-May-17  Employee's Annual Base Salary information is n...        7980
14    1-May-17          Employee's Gender is missing or incorrect         197
15    1-May-17                      Employee's address is missing        2424
16    1-May-17  Employee's contract type  information is not m...        2138
17    1-May-17  Employees (with only one PERNR) - IT9071 9000 ...      143777
18    1-May-17  Employees (with only one PERNR) - rem review p...       97002
19    1-May-17  Employees with multiple PERNR - IT9071 9000 re...        5789
20    1-May-17  Employees with multiple PERNR - rem review per...        5004
21    1-May-17       Employees with multiple position assignments        1049
22    1-May-17  Globally banded employees with IT9071 missing ...       81550
23    1-May-17               Headcount in Position 99999999 (All)         237
24    1-May-17                   Inconsistency PA vs. PD Job (PA)         385
25    1-May-17             Inconsistency PA vs. PD Org. Unit (PA)        3565
26    1-May-17              Inconsistency PA vs. PD Position (PA)         245
27    1-May-17  International Assignee IT9071 9000 rem review ...       15934
28    1-May-17  International Assignee rem review period shoul...       11251
29    1-May-17          Organisational Hierarchy Level  Incorrect         297
..         ...                                                ...         ...
859  31-Jul-17                 Employee FTE less than or equals 0       15966
860  31-Jul-17                 Employee Full Time FTE less than 1       16074
861  31-Jul-17                        Employee Job = 'Contractor'        1797
862  31-Jul-17                    Employee Nationality is missing        5014
863  31-Jul-17                  Employee with invalid Cost Center       87016
864  31-Jul-17                          Employee with missing job        7242
865  31-Jul-17                       Employee without Cost Center        5479
866  31-Jul-17  Employee's Annual Base Salary information is n...       89780
867  31-Jul-17          Employee's Gender is missing or incorrect       24228
868  31-Jul-17                      Employee's address is missing       14124
869  31-Jul-17  Employee's contract type  information is not m...       11340
870  31-Jul-17  Employees (with only one PERNR) - IT9071 9000 ...       73575
871  31-Jul-17  Employees (with only one PERNR) - rem review p...       58883
872  31-Jul-17  Employees with multiple PERNR - IT9071 9000 re...       27065
873  31-Jul-17  Employees with multiple PERNR - rem review per...       26605
874  31-Jul-17       Employees with multiple position assignments       13596
875  31-Jul-17  Globally banded employees with IT9071 missing ...       64050
876  31-Jul-17  Globally banded employees with IT9071 should n...     1776852
877  31-Jul-17               Headcount in Position 99999999 (All)       10148
878  31-Jul-17                   Inconsistency PA vs. PD Job (PA)        3462
879  31-Jul-17             Inconsistency PA vs. PD Org. Unit (PA)       43976
880  31-Jul-17  International Assignee IT9071 9000 rem review ...       13495
881  31-Jul-17  International Assignee rem review period shoul...       13262
882  31-Jul-17  Orphaned Headcount Outside Organisational Stru...        3561
883  31-Jul-17                    Position without job assignment        2459
884  31-Jul-17                 Project Contractor FTE more than 0        1779
885  31-Jul-17                  Terminated Employee Inconsistency       12465
886  31-Jul-17  This rule is checking if there is a valid reco...       13015
887  31-Jul-17  This rule is checking if there is just one val...       30828
888  31-Jul-17  Where Cost Centre in P0001 is not the same as ...       26445

     Error ID   Org Unit ID        PersNo   Position ID     Rule
0      229357  6.169366e+07  1.827968e+07  6.268286e+07     5811
1      117216  0.000000e+00  9.288087e+06  6.150259e+07     3816
2      385465  1.237860e+08  4.632958e+07  1.544931e+08     9695
3      230322  6.092518e+07  2.769585e+07  3.173592e+07     5796
4      307966  9.299301e+07  3.717908e+07  1.228465e+08     7724
5      692843  1.264561e+08  8.398180e+07  2.170522e+08    17343
6      768165  1.264669e+08  9.315557e+07  2.482615e+08    19300
7       75972  3.089938e+07  9.327106e+06  3.117007e+07     1933
8      246197  7.441018e+08  1.768163e+08  7.738434e+08    69012
9       76381  3.036942e+07  6.000257e+06  3.105740e+07     1929
10    1167630  8.659932e+08  2.750806e+08  1.083480e+09    68832
11     159707  6.095199e+07  2.760617e+07  9.166016e+07     5712
12      76613  3.032154e+07  9.160514e+06  3.006887e+07     1906
13    2313832  6.761664e+08  2.795939e+08  7.733228e+08    57660
14     691275  1.264792e+08  8.398162e+07  1.861680e+08    17145
15     692614  1.265251e+08  8.398196e+07  1.861355e+08    17334
16     769779  1.271544e+08  9.331351e+07  2.482082e+08    19190
17   10086534  3.563254e+09  1.508779e+09  4.347796e+09   339648
18   10494102  3.983855e+09  1.528757e+09  4.707956e+09   372259
19     436577  1.841387e+08  5.487211e+07  1.241009e+08    13657
20     602783  1.617463e+08  5.517290e+07  1.865311e+08    17532
21     536528  2.144097e+08  5.515770e+07  1.539793e+08    13398
22    9634858  3.169919e+09  1.367603e+09  4.226035e+09   301165
23    1171511  2.129478e+08  1.486348e+08  0.000000e+00    34236
24     545958  1.841150e+08  7.384598e+07  2.449584e+08    15280
25    3782976  1.025960e+09  3.286602e+08  7.988663e+08    95450
26     385845  1.231630e+08  4.623981e+07  1.532983e+08     9555
27    1279223  4.597149e+08  1.755421e+08  6.578694e+08    37050
28    1418955  5.524882e+08  1.949113e+08  5.812688e+08    42834
29      76604  3.060707e+07  0.000000e+00  0.000000e+00     1934
..        ...           ...           ...           ...      ...
859    753376  2.456808e+08  8.406391e+07  2.791180e+08    17343
860    751679  2.456808e+08  8.406391e+07  2.791180e+08    17370
861     75972  3.089938e+07  9.327106e+06  3.117007e+07     1933
862    202941  6.526465e+07  1.887231e+07  6.273184e+07     7668
863   4605133  1.988502e+09  6.267327e+08  2.215399e+09   139576
864    324739  9.236100e+07  3.657621e+07  1.244585e+08     7616
865    166573  6.180332e+07  1.831335e+07  6.200783e+07     3812
866   5617412  1.600213e+09  6.251607e+08  1.604134e+09   128774
867    752985  2.182222e+08  8.406679e+07  2.490853e+08    17145
868    671276  2.151650e+08  7.472588e+07  2.487790e+08    15408
869    755343  2.152938e+08  8.406697e+07  2.489141e+08    17271
870   1862427  6.154068e+08  1.922736e+08  5.224771e+08    52704
871   1293894  4.918639e+08  1.467919e+08  4.311917e+08    42878
872    748293  1.228314e+08  8.171884e+07  1.237733e+08    19510
873    809329  1.228955e+08  8.141882e+07  9.345314e+07    19480
874    919093  2.474769e+08  6.433267e+07  1.856732e+08    21054
875   2787583  8.306104e+08  2.683995e+08  8.630039e+08    68005
876  61832878  1.945290e+10  6.771211e+09  1.916018e+10  1539648
877    634198  3.034242e+07  7.423682e+07  0.000000e+00    15216
878    241957  6.164112e+07  2.740156e+07  9.361855e+07     5730
879   1340204  4.622223e+08  1.362408e+08  2.491873e+08    30544
880    235973  1.532365e+08  4.560487e+07  1.545328e+08     9750
881    335682  1.533977e+08  4.560487e+07  1.545328e+08     9735
882    166647  6.180332e+07  1.831335e+07  6.200783e+07     3806
883    156630  3.055768e+07  1.826286e+07  6.245069e+07     3826
884     83922  3.082524e+07  9.338798e+06  3.056793e+07     1928
885    168373  6.500791e+07  5.509141e+07  3.114700e+07    19150
886    839365  2.463790e+08  9.340816e+07  2.797652e+08    19210
887   2014884  7.099625e+08  2.236470e+08  7.138851e+08    46080
888    836351  3.090108e+08  9.060459e+07  1.564628e+08    19460

[889 rows x 8 columns]>

In [32]:
db.dq.insert_one(
    {
        'metrics2': ['grouped_errors']
    }
)